// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: "/Users/ctaylor/git/chplx/backend/build/../test/arr.chpl"
//
#include <hpx/hpx_init.hpp>

#include "arr.hpp"

int hpx_main(int argc, char ** argv) {

    #line 8 "../test/arr.chpl"
    std::vector<std::int64_t> k = {1,2,3,4,5};
    #line 9 "../test/arr.chpl"
    std::vector<std::vector<std::int64_t>> l = {{1,2},{3,4}};
    #line 10 "../test/arr.chpl"
    std::vector<std::vector<std::int64_t>> m = {{1},{2},{3,4,5}};
    #line 11 "../test/arr.chpl"
    std::vector<std::vector<std::int64_t>> n = {{1,2},{1,2}};
    #line 12 "../test/arr.chpl"
    std::vector<std::vector<std::vector<std::int64_t>>> o = {{{1,2},{1,2},{3,4}},{{5,6},{7,8}}};
    #line 13 "../test/arr.chpl"
    std::vector<std::vector<std::int64_t>> p = {{1,2,3,4,5}};
    #line 14 "../test/arr.chpl"
    std::vector<std::vector<std::vector<std::int64_t>>> q = {{{1,2,3,4,5}}};
    #line 16 "../test/arr.chpl"
    bool u;
    #line 17 "../test/arr.chpl"
    double v;
    #line 18 "../test/arr.chpl"
    std::uint8_t w;
    #line 19 "../test/arr.chpl"
    std::int64_t x;
    #line 20 "../test/arr.chpl"
    std::complex<double> y;
    #line 21 "../test/arr.chpl"
    std::string z;
    #line 23 "../test/arr.chpl"
    std::vector<std::int64_t> a(10);
    #line 24 "../test/arr.chpl"
    std::vector<double> b(10);
    #line 25 "../test/arr.chpl"
    std::vector<std::complex<double>> c(10);
    #line 26 "../test/arr.chpl"
    std::vector<std::string> d(10);
    #line 27 "../test/arr.chpl"
    std::vector<std::uint8_t> e(10);
    #line 28 "../test/arr.chpl"
    std::vector<bool> f(10);
    #line 30 "../test/arr.chpl"
    std::int64_t g = 1;
    #line 31 "../test/arr.chpl"
    bool h = true;
    #line 32 "../test/arr.chpl"
    std::string i = {"value"};
    #line 33 "../test/arr.chpl"
    double j = 1.000000;

    return hpx::finalize();
}

int main(int argc, char ** argv) {
    return hpx::init(argc, argv);
}