// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: "/Users/ctaylor/git/chplx/backend/build/../test/expr.chpl"
//
#include <hpx/hpx_init.hpp>

#include "expr.hpp"

int hpx_main(int argc, char ** argv) {

    #line 1 "../test/expr.chpl"
    std::int64_t a;
    #line 3 "../test/expr.chpl"
    a = 1 + 1;
    #line 4 "../test/expr.chpl"
    a = a + 1;
    #line 5 "../test/expr.chpl"
    a = 1 + a;
    #line 6 "../test/expr.chpl"
    a = a + a;
    #line 7 "../test/expr.chpl"
    a = ( a + a ) + a;
    #line 8 "../test/expr.chpl"
    a = ( a + a ) + 1;
    #line 9 "../test/expr.chpl"
    a = ( ( 1 + a ) + a ) + a;
    #line 10 "../test/expr.chpl"
    a = ( ( a + 1 ) + a ) + a;
    #line 11 "../test/expr.chpl"
    a = ( ( a + a ) + 1 ) + a;
    #line 12 "../test/expr.chpl"
    a = ( ( a + a ) + a ) + 1;
    #line 14 "../test/expr.chpl"
    void value() {
        #line 15 "../test/expr.chpl"
        std::int64_t b = 1;
        #line 16 "../test/expr.chpl"
        b = b + 1;
    }
    #line 19 "../test/expr.chpl"
    a = 1 + ( 1 + 1 );
    #line 20 "../test/expr.chpl"
    a = ( 1 + 1 ) + 1;
    #line 21 "../test/expr.chpl"
    a = a + ( ( a + a ) + a );
    #line 22 "../test/expr.chpl"
    a = ( ( a + a ) + a ) + a;
    #line 23 "../test/expr.chpl"
    a = 1 + ( 1 * 1 );
    #line 24 "../test/expr.chpl"
    a = 1 + a;
    #line 25 "../test/expr.chpl"
    a = a + a;
    #line 26 "../test/expr.chpl"
    a = a + ( a + a );
    #line 27 "../test/expr.chpl"
    a = ( a + a ) + a;
    #line 28 "../test/expr.chpl"
    a = a + ( ( a + a ) + a );
    #line 29 "../test/expr.chpl"
    a = ( ( a + a ) + a ) + a;

    return hpx::finalize();
}

int main(int argc, char ** argv) {
    return hpx::init(argc, argv);
}