// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: "/Users/ctaylor/git/chplx/backend/build/../test/fn.chpl"
//
#include <hpx/hpx_init.hpp>

#include "fn.hpp"

int hpx_main(int argc, char ** argv) {

    #line 11 "../test/fn.chpl"
    void print() {
        #line 12 "../test/fn.chpl"
        std::int64_t j;
        #line 13 "../test/fn.chpl"
        std::int64_t i = 1;
        #line 14 "../test/fn.chpl"
        bool k = true;
        #line 15 "../test/fn.chpl"
        double l = 1.000000;
        #line 16 "../test/fn.chpl"
        bool m;
        #line 17 "../test/fn.chpl"
        double n;
        #line 18 "../test/fn.chpl"
        std::cout << "a" << std::endl;
        #line 19 "../test/fn.chpl"
        std::cout << i << std::endl;
        #line 20 "../test/fn.chpl"
        std::cout << i << std::endl;
        #line 21 "../test/fn.chpl"
        std::cout << i << l << std::endl;
    }

    return hpx::finalize();
}

int main(int argc, char ** argv) {
    return hpx::init(argc, argv);
}