// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: heat.chpl
//
#pragma once

#ifndef __HEAT_HPP__
#define __HEAT_HPP__

#include <chplx.hpp>
#include <iostream>
#include <functional>
#line 1 "heat.chpl"
namespace heat {
    extern struct __thisModule *__this;

    #line 18 "heat.chpl"
extern std::int64_t ghosts;
    #line 19 "heat.chpl"
extern double k;
    #line 20 "heat.chpl"
extern double dt;
    #line 21 "heat.chpl"
extern double dx;
    #line 23 "heat.chpl"
extern std::int64_t nx;
    #line 24 "heat.chpl"
extern std::int64_t nt;
    #line 25 "heat.chpl"
extern std::int64_t threads;


    struct __thisModule {

        #line 31 "heat.chpl"
        void update(chplx::Array<double, chplx::Domain<1> > & d,chplx::Array<double, chplx::Domain<1> > & d2);

        static void __construct() { heat::__this = new __thisModule(); }

        static void __destruct() noexcept {
            auto *m = heat::__this;
            heat::__this = nullptr;
            delete m;
        }

        void __main();
    }; // end struct __thisModule

} // end namespace

#endif
