// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: heat.chpl
//
#pragma once

#ifndef __HEAT_DRIVER_HPP__
#define __HEAT_DRIVER_HPP__

#include <chplx.hpp>
#include "heat.hpp"

#endif
