// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: heateqn.chpl
//
#pragma once

#ifndef __HEATEQN_DRIVER_HPP__
#define __HEATEQN_DRIVER_HPP__

#include <chplx.hpp>
#include "heateqn.hpp"

#endif
