// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: gups_cpp.chpl
//
#include <hpx/hpx_init.hpp>
#include <hpx/program_options.hpp>

#include "gups_cpp_driver.hpp"

using namespace gups_cpp;

int hpx_main(int argc, char * argv[]) {
    gups_cpp::__this->__main();
    return hpx::finalize();
}

int main(int argc, char * argv[]) {
    chplx::registerModule<gups_cpp::__thisModule>();
    hpx::program_options::options_description options;
    options.add_options()
        ("memRatio",
            hpx::program_options::value(&gups_cpp::memRatio), "config var memRatio : std::int64_t");
    hpx::init_params init_args;
    init_args.desc_cmdline = options;
    return hpx::init(argc, argv, init_args);
}
