// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: gups_cpp.chpl
//
#pragma once

#ifndef __GUPS_CPP_DRIVER_HPP__
#define __GUPS_CPP_DRIVER_HPP__

#include <chplx.hpp>
#include "gups_cpp.hpp"

#endif
