// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: stream_cpp_triad.chpl
//
#pragma once

#ifndef __STREAM_CPP_TRIAD_HPP__
#define __STREAM_CPP_TRIAD_HPP__

#include <chplx.hpp>
#include <iostream>
#include <functional>
namespace stream_cpp_triad {
    extern struct __thisModule *__this;

    extern std::int64_t arraySize;


    struct __thisModule {

                auto randindex();
                void run(chplx::Array<double, chplx::Domain<1> > & A,chplx::Array<double, chplx::Domain<1> > & B,chplx::Array<double, chplx::Domain<1> > & C);

        static void __construct() { stream_cpp_triad::__this = new __thisModule(); }

        static void __destruct() noexcept {
            auto *m = stream_cpp_triad::__this;
            stream_cpp_triad::__this = nullptr;
            delete m;
        }

        void __main();
    }; // end struct __thisModule

} // end namespace

#endif
