#define CHPL_COMPILER_LIB_VERSION_MAJOR @CHPLX_FRONTEND_MAJOR_VERSION@
#define CHPL_COMPILER_LIB_VERSION_MINOR @CHPLX_FRONTEND_MINOR_VERSION@
#define CHPL_COMPILER_LIB_VERSION_PATCH @CHPLX_FRONTEND_PATCH_VERSION@
#define CHPL_CONFIGURED_PREFIX "@CMAKE_INSTALL_PREFIX@"
#define CHPL_BUILD_VERSION "@CHPLX_FRONTEND_BUILD_VERSION@"
#define CHPL_OFFICIAL_RELEASE @CHPLX_FRONTEND_OFFICIAL_RELEASE@
