#define CHPL_COMPILER_LIB_VERSION_MAJOR 1
#define CHPL_COMPILER_LIB_VERSION_MINOR 30
#define CHPL_COMPILER_LIB_VERSION_PATCH 0
#define CHPL_CONFIGURED_PREFIX "/usr/local"
#define CHPL_BUILD_VERSION "0"
#define CHPL_OFFICIAL_RELEASE 0
