// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: stream_cpp_add.chpl
//
#include <hpx/hpx_init.hpp>
#include <hpx/program_options.hpp>

#include "stream_cpp_add_driver.hpp"

using namespace stream_cpp_add;

int hpx_main(int argc, char * argv[]) {
    stream_cpp_add::__this->__main();
    return hpx::finalize();
}

int main(int argc, char * argv[]) {
    chplx::registerModule<stream_cpp_add::__thisModule>();
    hpx::program_options::options_description options;
    options.add_options()
        ("arraySize",
            hpx::program_options::value(&stream_cpp_add::arraySize), "config var arraySize : std::int64_t");
    hpx::init_params init_args;
    init_args.desc_cmdline = options;
    return hpx::init(argc, argv, init_args);
}
