// This program file was generated by the chplx compiler.
// The original Chapel program file can be found here: stream_cpp_copy.chpl
//
#pragma once

#ifndef __STREAM_CPP_COPY_DRIVER_HPP__
#define __STREAM_CPP_COPY_DRIVER_HPP__

#include <chplx.hpp>
#include "stream_cpp_copy.hpp"

#endif
