# Copyright (c) 2023 Hartmut Kaiser
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI using build script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install llvm, clang 17
      shell: bash
      run: |
          sudo apt purge llvm-16 clang-16 llvm-17 llvm-18 clang-17 clang-18 -y || true
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17
          sudo apt install libclang-17-dev -y

    - name: Build only ChplX using provided script
      shell: bash
      run: |
          python3 benchmark.py --build-only

